<?php
/**
 * @var $block \Razoyo\AnimalProfile\Block\Profile\Photo
 */
?>
<p><?= $block->getGreeting() ?></p>
<p>
    <select name="animal" id="select-animal">
        <option selected="true" disabled="disabled" value=''>Choose Profile Picture</option>
        <option value='cat'>Cat</option>
        <option value='dog'>Dog</option>
        <option value='llama'>Llama</option>
        <option value='anteater'>Anteater</option>
    </select>
</p>
<div id="animalid-photo"></div>
<script type="text/x-magento-init">
    {
        "#select-animal": {
            "select-animal-profile": {
                "profileDiv": "#animalid-photo",
                "profilePhoto": "<?= $block->getPhotoUrl() ?>"
            }
        }
    }
</script>